openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:9091
    description: Generated server url
paths:
  /v1/d/prompt:
    get:
      tags:
        - dashboard-controller
      operationId: getPrompt
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PromptResponse"
    post:
      tags:
        - dashboard-controller
      operationId: prompt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
  /v1/d/recent:
    get:
      tags:
        - dashboard-controller
      operationId: recentPrompts
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PromptResponse"
components:
  schemas:
    PromptRequest:
      properties:
        userId:
          type: integer
          format: int64
        groupId:
          type: integer
          format: int64
        prompt:
          type: string
        timeZone:
          properties:
            displayName:
              type: string
            id:
              type: string
            dstsavings:
              type: integer
              format: int32
            rawOffset:
              type: integer
              format: int32
    PromptResponse:
      properties:
        userId:
          type: integer
          format: int64
        groupId:
          type: integer
          format: int64
        prompt:
          type: string
        createdAt:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - CREATED
            - QUERY_GENERATION
            - QUERY_GENERATION_FAILED
            - DATA_COLLECTION
            - DATA_COLLECTION_FAILED
            - COMPLETED
        metaData:
          type: string
        tags:
          type: array
          items:
            type: string
        errorMessage:
          type: string
        thumbnailUrl:
          type: string
