name: Merge OpenAPI Specs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Ensure the token has write permissions

jobs:
  merge-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge OpenAPI YAML files using npx, excluding sb-openapi-spec.yml
        run: |
          SPEC_DIR=$(pwd)
          OUTPUT_FILE="$SPEC_DIR/sb-openapi-spec.yml"
          OPENAPI_FILES=$(find $SPEC_DIR -name "sb-openapi*.yml" | grep -v "sb-openapi-spec.yml")
          npx @redocly/cli join $OPENAPI_FILES -o $OUTPUT_FILE
          echo "OpenAPI files merged into $OUTPUT_FILE"

      - name: Update 'servers' URLs to remove port numbers
        run: |
          SPEC_DIR=$(pwd)
          OUTPUT_FILE="$SPEC_DIR/sb-openapi-spec.yml"
          sed -i 's|http://app.stockbinger.com:[0-9]*|https://app.stockbinger.com|g' $OUTPUT_FILE
          sed -i 's|https://app.stockbinger.com:[0-9]*|https://app.stockbinger.com|g' $OUTPUT_FILE
          sed -i 's|http://localhost:[0-9]*|https://app.stockbinger.com|g' $OUTPUT_FILE
          sed -i 's|http://127.0.0.1:[0-9]*|https://app.stockbinger.com|g' $OUTPUT_FILE
          echo "Updated servers URL in OpenAPI spec."

      - name: Commit and Push Merged OpenAPI Spec
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add sb-openapi-spec.yml
          git commit -m "Merge and update OpenAPI specs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
